import Header from "../components/layout/Header";
import AppProvider from "../components/AppContext";
import { Roboto } from "next/font/google";
import "./globals.css";
import toast, { Toaster } from "react-hot-toast";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "DeliverEats",
  description: "Generated by Julio Condor",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="flex flex-col min-h-screen">
        <main className="max-w-4xl mx-auto p-2 flex-grow">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
          </AppProvider>
        </main>
        <footer className="font-normal text-gray-600 p-4 border-t ">
              <p className="text-center">&copy; 2023 All rights reserved</p>
              <p className="text-center">
                Designed by {" "}
                <a
                  className="hover:text-fuchsia-500 transition-colors duration-500 font-bold"
                  href="https://github.com/ravenbbs"
                  target="_blank"
                >
                  ravenbbs
                </a>
              </p>
        </footer>
      </body>
    </html>
  );
}
